controllers/LoanController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Loan;
use app\models\LoanSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * This controller is used for crud operations
 */
class LoanController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Loan models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new LoanSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Create a new loan
     * @return mixed
     */
    public function actionCreate($userId = null)
    {
        $model = new Loan();
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            $model->user_id = $userId;
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Update one loan
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Delete one loan
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * View one loan
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * loan find model. If model does not exist redirected to http code page.
     * @param integer $id
     * @return Loan the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Loan::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use app\models\User;
use app\models\UserSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\Loan;

/**
 * This controller is used for crud operations
 */
class UserController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Create a new User model
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new User();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Update one user
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes one user
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * View one user
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $user = $this->findModel($id);
        $user->getPersonsAge($user['personal_code']);

        //User's debt calculation
        $loan = new Loan();
        $usersLoans = $loan->find()->where(['user_id' => $id, 'status' => 1])->all();

        $totalAmount = 0;
        foreach ($usersLoans as $loan):
            $totalAmount += $loan->amount;
        endforeach;
        //end_date Calculation
        return $this->render('view', [
            'model' => $this->findModel($id),
            'age' => $user->getPersonsAge($user->personal_code),
            'birthday' => $user->getPersonsBirthday($user->personal_code),
            'totalAmount' => $totalAmount
        ]);
    }

    /**
     * user find model. If model does not exist redirected to http code page.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'options' => [
            'class' => 'navbar-inverse'
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-inverse navbar-nav navbar-left'],
        'encodeLabels' => false,
        'items' => [
            ['label' => 'Klienditeenindus', 'url' => ['#']],
            ['label' => "<span class='glyphicon glyphicon-phone'></span> 1715",  'url' => ['#'],],
            ['label' => "<span class='glyphicon glyphicon-time'></span> E-P 9.00-21.00", 'url' => ['#']],
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-inverse navbar-nav navbar-right'],
        'encodeLabels' => false,
        'items' => [
            '<li>'.Html::a("Tere, Kaupo Kasutaja", ['#']).'</li>',
            '<li>'.Html::a("<span class='glyphicon glyphicon-lock'></span> LOG OUT", ['/user/logout'], ['class'=>'button-orange','data-method' => 'post']).'</li>'
        ],
    ]);
    NavBar::end();
    ?>
    <?php
    NavBar::begin([
        'options' => [
            'class' => 'navbar secondNav',
        ],
        'brandLabel' => Html::img('@web/assets/cs_logo.png', ['alt'=>'','class'=>'headerLogo']),
        'brandUrl' => Yii::$app->homeUrl,

    ]);

    echo Nav::widget([
        'options' => ['class' => 'navbar navbar-nav navbar-left' ],
        'encodeLabels' => false,
        'items' => [
            ['label'=>'How it works<span class="glyphicon glyphicon-chevron-right orng-col"></span>','url'=>['https://www.creditstar.co.uk/site/howitworks/firstloan']],
            ['label'=>'Help centre<span class="glyphicon glyphicon-chevron-right orng-col"></span>','url'=>['https://www.creditstar.co.uk/site/help/faq']],
            ['label'=>'About us<span class="glyphicon glyphicon-chevron-right orng-col"></span>', 'url' => ['https://www.creditstar.co.uk/site/about']],
            ['label'=>'Responsible Lending<span class="glyphicon glyphicon-chevron-right orng-col"></span>', 'url' => ['https://www.creditstar.co.uk/site/responsible']],
        ],
    ]);
    echo Nav::widget([
        'options' => [
            'class'=>'navbar text-small text-right navbar-nav navbar-right'
        ],
        'encodeLabels' => false,
        'items' => [
            ['label'=>'По-русски','url'=>['#'],'class'=>'text-small'],
        ],

    ]);

    NavBar::end();
    ?>
    <div class="navPills">
        <div class="container">
            <div class="row">
                <div class="col-md-offset-1 col-xs-11 col-sm-11 col-md-11">
                    <ul class="nav nav-pills">
                        <li role="presentation"><?php echo Html::a("My Actions", ['#']);?></li>
                        <li role="presentation"><?php echo Html::a("Users", ['/user/index']);?></li>
                        <li role="presentation"><?php echo Html::a("Loans", ['/loan/index']);?></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="container creditstarContainer">
        <div class="corner-ribbon top-left sticky red shadow"><span class="ribbonIcon glyphicon glyphicon-share-alt"></span></div>

        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>