models/User.php
<?php

namespace app\models;

use Yii;

/**
 * user model
 *
 * @property integer $id
 * @property string $first_name
 * @property string $last_name
 * @property string $email
 * @property integer $personal_code
 * @property integer $phone
 * @property boolean $active
 * @property boolean $dead
 * @property string $lang
 */
class User extends \yii\db\ActiveRecord implements \yii\web\IdentityInterface
{
    //Removed because it conflicts with User Id
    //public $id;
    public $username;
    public $password;
    public $authKey;
    public $accessToken;
    private static $users = [
        '100' => [
            'id' => '100',
            'username' => 'admin',
            'password' => 'admin',
            'authKey' => 'test100key',
            'accessToken' => '100-token',
        ],
        '101' => [
            'id' => '101',
            'username' => 'demo',
            'password' => 'demo',
            'authKey' => 'test101key',
            'accessToken' => '101-token',
        ],
    ];

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'user';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['first_name', 'last_name', 'email', 'personal_code', 'phone'], 'required'],
            [['first_name', 'last_name', 'email', 'lang'], 'string'],
            [['email'], 'email'],
            [['phone'], 'integer'],
            [
                ['personal_code'],
                'validatePersonalCode',
                'message' => 'Please input a valid personal identification number.'
            ],
            [['active', 'dead'], 'boolean'],
        ];
    }

    /**
     * All user attributes
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id'            => 'User Id',
            'first_name'    => 'First Name',
            'last_name'     => 'Last Name',
            'email'         => 'Email',
            'personal_code' => 'Personal Code',
            'phone'         => 'Phone',
            'active'        => 'Active',
            'dead'          => 'Is Dead?',
            'lang'          => 'Lang',

        ];
    }

    /**
     * user hasMany loan foreignKey
     * @return \yii\db\ActiveQuery
     */
    public function getLoans()
    {
        return $this->hasMany(Loan::className(), ['user_id' => 'id']);
    }

    /**
     * Calculate person age
     * @param integer $personCode
     */
    public function getPersonsAge($personCode)
    {
        $year = substr($personCode, 1, 2);
        $month = preg_replace('/^0/', '', substr($personCode, 3, 2));
        $day = preg_replace('/^0/', '', substr($personCode, 5, 2));
        $personFirstNumber = substr($personCode, 0, 1);
        if ($personFirstNumber === '1' || $personFirstNumber === '2') {
            $year += 1800;
        } else {
            if ($personFirstNumber === '3' || $personFirstNumber === '4') {
                $year += 1900;
            } else {
                if ($personFirstNumber === '5' || $personFirstNumber === '6') {
                    $year += 2000;
                } else {
                    $year += 2100;
                }
            }
        }
        $birthday = $year . "-" . $month . "-" . $day;
        $from = new \DateTime($birthday);
        $today = new \DateTime('today');
        if ($from > $today) {
            return 0;
        }

        return $from->diff($today)->y;
    }

    /**
     * Returns the birthdate in YYYY-MM-DD format
     * @param unknown $personCode
     */
    public function getPersonsBirthday($personCode)
    {
        $year = substr($personCode, 1, 2);
        $month = preg_replace('/^0/', '', substr($personCode, 3, 2));
        $day = preg_replace('/^0/', '', substr($personCode, 5, 2));
        $firstNumber = substr($personCode, 0, 1);
        if ($firstNumber === '1' || $firstNumber === '2') {
            $year += 1800;
        } else {
            if ($firstNumber === '3' || $firstNumber === '4') {
                $year += 1900;
            } else {
                if ($firstNumber === '5' || $firstNumber === '6') {
                    $year += 2000;
                } else {
                    $year += 2100;
                }
            }
        }
        $birthday = $year . "-" . $month . "-" . $day;
        return $birthday;
    }

    /**
     * check personal_code
     * @param integer $personCode
     * @return number
     */
    private function personalCodeControlNumber($personCode)
    {
        $multiplier1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 1];
        $multiplier2 = [3, 4, 5, 6, 7, 8, 9, 1, 2, 3];
        $mod = null;
        $total = 0;

        for ($i = 0; $i < 10; $i++) {
            $total += substr($personCode, $i, 1) * $multiplier1[$i];
        }
        $mod = $total % 11;

        $total = 0;
        if (10 === $mod) {
            for ($i = 0; $i < 10; $i++) {
                $total += substr($personCode, $i, 1) * $multiplier2[$i];
            }
            $mod = $total % 11;
            if (10 === $mod) {
                $mod = 0;
            }
        }

        return $mod;
    }

    /**
     * check validate personal_code
     * @param $var
     * @return bool
     */
    public function validatePersonalCode($var)
    {
        if (strlen($this->$var) != 11) {
            $this->addError('personal_code', 'Not a valid Personal Code');

            return false;
        }
        $control = $this->personalCodeControlNumber($this->$var);
        if ($control != substr($this->$var, 10, 1)) {
            $this->addError('personal_code', 'Not a valid Personal Code');

            return false;
        }
        return true;
    }
    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return isset(self::$users[$id]) ? new static(self::$users[$id]) : null;
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        foreach (self::$users as $user) {
            if ($user['accessToken'] === $token) {
                return new static($user);
            }
        }
        return null;
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        foreach (self::$users as $user) {
            if (strcasecmp($user['username'], $username) === 0) {
                return new static($user);
            }
        }
        return null;
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->authKey;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->authKey === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return $this->password === $password;
    }
}

controllers/LoanController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Loan;
use app\models\LoanSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * This controller is used for crud operations
 */
class LoanController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Loan models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new LoanSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Create a new loan
     * @return mixed
     */
    public function actionCreate($userId = null)
    {
        $model = new Loan();
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            $model->user_id = $userId;
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Update one loan
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Delete one loan
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * View one loan
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * loan find model. If model does not exist redirected to http code page.
     * @param integer $id
     * @return Loan the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Loan::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use app\models\User;
use app\models\UserSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\Loan;

/**
 * This controller is used for crud operations
 */
class UserController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Create a new User model
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new User();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Update one user
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes one user
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * View one user
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $user = $this->findModel($id);
        $user->getPersonsAge($user['personal_code']);

        //User's debt calculation
        $loan = new Loan();
        $usersLoans = $loan->find()->where(['user_id' => $id, 'status' => 1])->all();

        $totalAmount = 0;
        foreach ($usersLoans as $loan):
            $totalAmount += $loan->amount;
        endforeach;
        //end_date Calculation
        return $this->render('view', [
            'model' => $this->findModel($id),
            'age' => $user->getPersonsAge($user->personal_code),
            'birthday' => $user->getPersonsBirthday($user->personal_code),
            'totalAmount' => $totalAmount
        ]);
    }

    /**
     * user find model. If model does not exist redirected to http code page.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/user/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\User */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'first_name')->textInput() ?>

    <?= $form->field($model, 'last_name')->textInput() ?>

    <?= $form->field($model, 'email')->textInput() ?>

    <?= $form->field($model, 'personal_code')->textInput() ?>

    <?= $form->field($model, 'phone')->textInput() ?>

    <?= $form->field($model, 'active')->checkbox() ?>

    <?= $form->field($model, 'dead')->checkbox() ?>

    <?= $form->field($model, 'lang')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/user/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\UserSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'first_name') ?>

    <?= $form->field($model, 'last_name') ?>

    <?= $form->field($model, 'email') ?>

    <?= $form->field($model, 'personal_code') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/user/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = 'Create User';
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/user/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\UserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Users';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-index">
    <h1><?= Html::encode($this->title) ?></h1>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
    	'tableOptions' => ['class' => 'table table-hover'],
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'id',
            'first_name:ntext',
            'last_name:ntext',
            'email:ntext',
             'personal_code',
             'phone',
             'active:boolean',
             'dead:boolean',
             'lang:ntext',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    	'rowOptions'=>function($model){
    		if($model->dead == 1){
    			return ['class' => 'redRow'];
    		}
    		if($model->active == 0){
    			return ['class' => 'yellowRow'];
    		}
        },
    ]); ?>
</div>
<p>
        <?= Html::a('Create User', ['create'], ['class' => 'button-orange button-large']) ?>
</p>

views/user/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = 'Update User: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="user-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/user/view.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\data\ActiveDataProvider;;
$formatter = \Yii::$app->formatter;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = $model->first_name.' '.$model->last_name;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
$dataProvider = new ActiveDataProvider([
		'query' => $model->getLoans(),
		'pagination' => [
				'pageSize' => 20,
		],
]);
?>
<div class="user-view">

    <h1><?= Html::encode($this->title) ?></h1>
    <div class="row">
    <div class="col-md-2">
    <br>
    <h4>Currently to be Paid: </h4>
    </div>
    <div class="col-md-4">
    <h2><?php echo $formatter->asCurrency($totalAmount,'EUR');?></h2>
    </div>
    <div class="col-md-offset-2 col-md-4 text-center textRed">
    <h1><?= $age;?></h1>
    <small>User's Age</small>
    </div>
    </div>
    <br>

    <?= GridView::widget([
    	'dataProvider' => $dataProvider,
    	'tableOptions' => ['class' => 'table table-hover'],
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'id',
            'user_id',
            'amount',
            'interest',
            'duration',
            'start_date',
            'end_date',
            'campaign',
            'status:boolean',
            [
             'class' => 'yii\grid\ActionColumn',
             'controller'=>'loan'
    		],
        ],
    	'rowOptions'=>function($model){
    	if($model->campaign== 7){
    		return ['class' => 'redRow'];
    	}
    	if($model->campaign== 6){
    		return ['class' => 'yellowRow'];
    	}
    	if($model->campaign== 3){
    		return ['class' => 'disabledRow'];
    	}
    },
    ]); ?>
</div>
    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'button-orange button-large']) ?>
        <?= Html::a('Create Loan', ['loan/create', 'userId' => $model->id], ['class' => 'button-orange button-large']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'button-warning button-large',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>